---
# Preparations
- name: "Install R depended packages"
  yum:
    name: "{{ packages }}"
    state: latest

# Compilation & Installing
- name: Check for R installation @ {{ r_install_dest }}
  stat: path={{ r_install_dest }}/{{ r_prefix }}
  register: r_installed

- name: "Copy and extract the R src package, configure, make and install R and make link"
  block:
    - unarchive:
        src: "files/{{ r_prefix }}.{{ r_archive }}"
        dest: /tmp
    - command: "./configure --prefix={{ r_install_dest }}/{{ r_prefix }} {{ r_configure_flags | join(' ') }}"
      args:
        chdir: /tmp/{{ r_prefix }}
    - make:
        chdir: /tmp/{{ r_prefix }}
    - make:
        chdir: /tmp/{{ r_prefix }}
        target: install
      become: yes
    - file:
        src: "{{ r_install_dest }}/{{ r_prefix }}"
        dest: "{{ r_linkdir }}"
        state: link
      when: r_dolink
  when: not r_installed.stat.exists
 
# Configuring Slurm man files
- name: "Install man-db package"
  yum:
    name: man-db
    state: latest
      
- name: "Set R MANDATORY_MANPATH"
  lineinfile:
    path: /etc/man_db.conf
    regexp: 'MANDATORY_MANPATH                       {{ r_linkdir }}/share/man'
    insertafter: '^MANDATORY_MANPATH'
    line: 'MANDATORY_MANPATH                       {{ r_linkdir }}/share/man'
    state: present

- name: "Set R bin MANPATH_MAP"
  lineinfile:
    path: /etc/man_db.conf
    regexp: 'MANPATH_MAP     {{ r_linkdir }}/bin          {{ r_linkdir }}/share/man'
    insertafter: '^MANPATH_MAP'
    line: 'MANPATH_MAP     {{ r_linkdir }}/bin          {{ r_linkdir }}/share/man'
    state: present
    
- name: "Run mandb to reconfigure man databases"
  command: mandb

# Set Slurm PATHs (create file in profile.d)
- name: "Create profile.d files with PATH info"
  template: 
    src: r.sh.j2
    dest: /etc/profile.d/r.sh
    owner: root
    group: root
    mode: 0644 

- name: "Make link for csh users"
  file:
    src: /etc/profile.d/r.sh
    dest: /etc/profile.d/r.csh
    state: link

# Install Bioconductor R and CRAN packages from provided rda file containing "pkgs" variable
- block: 
  - name: "Copy {{ r_packages }} to server"
    copy:
      src: "{{ playbook_dir }}/{{ r_packages }}"
      dest: "/tmp/{{ r_packages }}"
  - name: "Install cran / bioconductor packages" 
    command: "{{ r_install_dest }}/{{ r_prefix}}/bin/Rscript -e 'install.packages(\"BiocManager\", repos=\"{{ r_rpos }}\");load(\"/tmp/{{ r_packages }}\");BiocManager::install(pkgs={{ r_packages_var }})'"
    register: instpack
  - copy: content={{ instpack.stdout }} dest=/tmp/r_instpack.stdout
  - copy: content={{ instpack.stderr }} dest=/tmp/r_instpack.stderr
  when: r_packages is defined

#
# Install github packages with devtools ( https://cran.r-project.org/web/packages/devtools/index.html )
# Package list is defined in r_github_packages variable.
#
- block:
  - name: "Install 'devtools' package"
    command: "{{ r_install_dest }}/{{ r_prefix }}/bin/Rscript -e 'install.packages(\"devtools\", repos=\"{{ r_rpos }}\");'"
  - name: "Install github packages"
    command: "{{ r_install_dest }}/{{ r_prefix }}/bin/Rscript -e 'require(\"devtools\");devtools::install_github(\"{{ item }}\");'"      
    register: instgithub
    loop: "{{ r_github_packages }}"
  - copy: content={{ instgithub.results }} dest=/tmp/r_instgithub.results  
  when: r_github_packages is defined

#
# Install packages from source 
#
# Packages are defined in r_source_packages variable.
#
- block:
  - name: "Install source only packages"
    command: "{{ r_install_dest }}/{{ r_prefix }}/bin/Rscript -e 'install.packages(\"{{ item }}\", repos=NULL, method=\"libcurl\");'"
    register: instsource
    loop: "{{ r_source_packages }}"
  - copy: content={{ instsource.results }} dest=/tmp/r_instsource.results
  when: r_source_packages is defined
