---
#
# Configuration file - from template
#
krb5_config_file: /etc/krb5.conf          #Destination
krb5_template_file: krb5.conf.j2          #Template file

#Realm Config
realm_name: EXAMPLE.COM
kdcs:
  - { hostname: KDC, port: 88 }
admins:
  - { hostname: ADMIN, port: 749 }
