---
- name: Enable RHSM repository
  community.general.rhsm_repository:
    name: "{{ epel_repos }}"

- name: Install the epel rpm from a remote repo
  ansible.builtin.yum:
    name: "{{ epel_package_name }}"
    disable_gpg_check: true
    state: present
