---
#Source prefix
perl_prefix: perl-5.28.1 

#Source archive ext 
perl_archive: tar.gz

#Configure flags add empty list as default ([])
perl_configure_flags: []

#Install desination (prefix) on destination machine
perl_install_dest: /opt/software/versions

#Link location where install destination is linked to and configuration and script files are pointed at 
perl_linkdir: /opt/software/perl

#Do the link (for safe installations)
perl_dolink: true 

#List of perl packages to be installed from CPAN (and their OS dependencies)
#
# In order to get a list of installed packages:
# perldoc perllocal   <- this will start less/more a file generated in /tmp 
# cat /tmp/the_gen_file  | grep -v "*" | sed  '/^$/d' | cut -c42- | sort
#
# empty list as default: []
#
perl_packages_os_dependencies: []
perl_packages: []

#Additional library locations
perl_perl5lib:
 - /opt/software/perl5
 - /opt/tools/perl5

#Common user and group id
r_uid: root
r_gid: root

