---
#Source prefix
r_prefix: R-4.1.1

#Source archive ext
r_archive: tar.gz

#Configure flags (2do: add in tasks - when needed!) add empty list as default ([])
r_configure_flags:
 - "--with-x=yes"
 - "--with-cairo=yes"
 - "--with-libpng=yes"
 - "--enable-R-shlib"
 - "--enable-memory-profiling"

#Install desination (prefix) on destination machine
r_install_dest: /opt

#Link location where install destination is linked to and configuration and script files are pointed at
r_linkdir: /opt/R
#Do the link (for safe installations)
r_dolink: true

#Location of R repositories
r_rpos: "https://mirror.lyrahosting.com/CRAN/"

#One instalation (provide host name) - in cluster situations with central nfs storage of software / tools
#r_one_installation: hostname

#OS Dependencies for packages (RPMs)
#r_os_packages: []

#List of bioconductor and CRAN packages
#r_packages: []

#Location of list of bioconductor packages ( expects in: playbook_dir ) - uses bioclite to install both CRAN and bioconductor packages
#r_rda_packages: r_packages.rda

#Variable name of packages in packages file
r_rda_packages_var: pkgs

#List with github identifications - make sure deps are arranged!
#r_github_packages:

#List with gitlab identifications - make sure deps!
#r_gitlab_packages:

#List with web locations of source packages (outside CRAN / Bioconductor) - make sure deps are arranged!
#r_source_packages:

#R common user and group id
r_uid: root
r_gid: root

