---
#
# Source archive (prefix and archive), looks for (link) in files/ folder of role
#
plink_prefix: plink-1.07-src
plink_archive: zip

#Installation folder
plink_install_dest: /opt/tools/versions

#Separate link dir (for different versions)
plink_linkdir: /opt/tools/plink

#Binaries (e.g. linking to location in PATH)
plink_binary_source: /opt/tools/plink/plink
plink_binary_dest: /opt/tools/bin/plink

#Do the actual linking?
plink_dolink: true
