---
- name: install prerequisites
  ansible.builtin.yum:
    name: "{{ gitlab_packages }}"
  register: gitlab_packages_installed

- name: start/enable services
  ansible.builtin.systemd:
    name: "{{ service }}"
    enabled: yes
    state: started
  loop_control:
    loop_var: service
  loop:
    - sshd
    - postfix
  when:
    - gitlab_packages_installed.changed
