---
- name: "Install Kerberos 5 packages"
  yum:
    name: "{{ packages }}"
    state: latest  

- name: "'{{ krb5_config_file }}' stat"
  stat: path={{ krb5_config_file }}
  register: krb5_cfg_present

- name: "Backup {{ krb5_config_file }}"
  copy:
    remote_src: yes
    src: "{{ krb5_config_file }}" 
    dest: "{{ krb5_config_file }}.{{ ansible_date_time.epoch }}.bak"
  when: krb5_cfg_present.stat.exists

- name: "Create new {{krb5_config_file }}"
  template:
    src: "{{ krb5_template_file }}"
    dest: "{{ krb5_config_file }}"
    owner: root
    group: root
    mode: 0644

- name: "Configure system authentication resources"
  command: "authconfig --enablekrb5 --krb5kdc={{ kdc_hostname|upper() }}.{{ realm_name|upper()}}:{{ kdc_port }} --krb5adminserver={{ admin_hostname|upper() }}.{{ realm_name|upper() }}:{{ admin_port }} --krb5realm={{ realm_name|upper() }} --update"

- name:  "Enable pam mkhomedir"
  command: "authconfig --enablemkhomedir --update"
