---
- name: "Install Kerberos 5 packages"
  yum:
    name: "{{ adauth_packages }}"
    state: latest

- name: "'{{ adauth_krb5_config_file }}' stat"
  stat: path={{ adauth_krb5_config_file }}
  register: adauth_krb5_cfg_present

- name: "Backup {{ adauth_krb5_config_file }}"
  copy:
    remote_src: yes
    src: "{{ adauth_krb5_config_file }}"
    dest: "{{ adauth_krb5_config_file }}.{{ ansible_date_time.epoch }}.bak"
  when: adauth_krb5_cfg_present.stat.exists

- name: "Create new {{ adauth_krb5_config_file }}"
  template:
    src: "{{ adauth_krb5_template_file }}"
    dest: "{{ adauth_krb5_config_file }}"
    owner: root
    group: root
    mode: 0644

# name: "Configure system authentication resources"
# command: "authconfig --enablekrb5 --krb5kdc={{ kdc_hostname|upper() }}.{{ realm_name|upper()}}:{{ kdc_port }} --krb5adminserver={{ admin_hostname|upper() }}.{{ realm_name|upper() }}:{{ admin_port }} --krb5realm={{ realm_name|upper() }} --update"
# command: "authconfig --enablekrb5 --krb5kdc={{ adauth_kdcs.hostname|upper() }}.{{ adauth_realm_name|upper() }}:{{ adauth_kdcs.port }}

- name: "Enable krb5"
  command: "authconfig --enablekrb5 --update"

- name:  "Enable pam mkhomedir"
  command: "authconfig --enablemkhomedir --update"
