---

# Preparations
- name: "Install Python depended packages"
  yum:
    name: "{{ python2_os_packages }}"
    state: latest
  become: true

# Compilation & Installing
- name: Check for Python installation @ {{ python2_install_dest }}
  stat: path={{ python2_install_dest }}/{{ python2_prefix }}
  register: python2_installed

- name: "Copy and extract the Python src package, configure, make and install Python.."
  block:
    - unarchive:
        src: "files/{{ python2_prefix }}.{{ python2_archive }}"
        dest: /tmp
      when: python2_one_installation is not defined or inventory_hostname == python2_one_installation
    - command: "./configure --prefix={{ python2_install_dest }}/{{ python2_prefix }} {{ python2_configure_flags | join(' ') }} {{ python2_configure_flags_user | join(' ') }}"
      args:
        chdir: /tmp/{{ python2_prefix }}
      when: python2_one_installation is not defined or inventory_hostname == python2_one_installation
    - make:
        chdir: /tmp/{{ python2_prefix }}
      when: python2_one_installation is not defined or inventory_hostname == python2_one_installation
    - make:
        chdir: /tmp/{{ python2_prefix }}
        target: install
      when: python2_one_installation is not defined or inventory_hostname == python2_one_installation
  when: not python2_installed.stat.exists

- name: "Check if link exists.."
  stat: "path={{ python2_linkdir }}"
  register: python2_linked

- name: "Create link.."
  file:
    src: "{{ python2_install_dest}}/{{ python2_prefix }}"
    dest: "{{ python2_linkdir }}"
    state: link
  ignore_errors: yes                                 #Taking a small risk here - this config should allow overlapping links and different links per node
  when: python2_dolink and not python2_linked.stat.exists

# Configuring Python man directories

- name: "Set python MANDATORY_MANPATH"
  lineinfile:
    path: /etc/man_db.conf
    regexp: 'MANDATORY_MANPATH                       {{ python2_linkdir }}/share/man'
    insertafter: '^MANDATORY_MANPATH'
    line: 'MANDATORY_MANPATH                       {{ python2_linkdir }}/share/man'
    state: present
  become: true

- name: "Set python bin MANPATH_MAP"
  lineinfile:
    path: /etc/man_db.conf
    regexp: 'MANPATH_MAP     {{ python2_linkdir }}/bin          {{ python2_linkdir }}/share/man'
    insertafter: '^MANPATH_MAP'
    line: 'MANPATH_MAP     {{ python2_linkdir }}/bin          {{ python2_linkdir }}/share/man'
    state: present
  become: true

- name: "Run mandb to reconfigure man databases"
  command: mandb
  become: true

# Set Python settings with file in profile.d)
- name: "Create profile.d files with PATH info"
  template:
    src: python2.sh.CentOS.j2
    dest: "/etc/profile.d/{{ python2_profile_d_file }}.sh"
    owner: root
    group: root
    mode: 0644
  become: true

- name: "Make link for csh users"
  file:
    src: "/etc/profile.d/{{ python2_profile_d_file }}.sh"
    dest: "/etc/profile.d/{{ python2_profile_d_file }}.csh"
    state: link
  become: true

# Set Python lib dirs
- name: "Create ld.so.conf.d file with lib info"
  template:
    src: python2.conf.j2
    dest: "/etc/ld.so.conf.d/{{ python2_lib_conf_file }}.conf"
    owner: root
    group: root
    mode: 0644
  become: true

#Make sure we are working with the newest version of seuptools / pip / virtualenv
- name: "Update pip"
  command: "{{ python2_install_dest }}/{{ python2_prefix }}/bin/{{ python2_pip }} install --upgrade pip"
  when: python2_one_installation is not defined or inventory_hostname == python2_one_installation
- name: "Install setuptools and virtualenv"
  command: "{{ python2_install_dest }}/{{ python2_prefix }}/bin/{{ python2_pip }} install setuptools virtualenv"
  when: python2_one_installation is not defined or inventory_hostname == python2_one_installation

- name: "Install OS packages for additional python libraries"
  yum:
    name: "{{ python2_packages_os_dependencies }}"
    state: latest
  become: true

- name: "Install additional python libraries"
  block:
    - command: "{{ python2_install_dest }}/{{ python2_prefix }}/bin/{{ python2_pip }} install {{ item }}"
      loop: "{{ python2_packages }}"
      ignore_errors: yes
      register: instpythonpackages
    - copy: content={{ instpythonpackages }} dest=/tmp/{{ python2_prefix }}-inst.packages.log
  when: python2_packages is defined and ( python2_one_installation is not defined or inventory_hostname == python2_one_installation )
