---
# system user that runs slurm
slurm_user: slurm

# Slurm RPMs
slurm_packages:
  - slurm
  - slurm-slurmd
  - slurm-slurmctld
  - slurm-slurmdbd
  - slurm-gui
  - slurm-doc
  - libcgroup
  - libcgroup-tools

#
# This role is configured for mysql or mariadb databases
#
slurm_dbd_packages:
  - mariadb
  - mariadb-server

slurm_db_daemon_name: mariadb
