---
- name: gather os specific variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', python3_vars_params) }}"
  vars:
    python3_vars_params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
      paths:
        - '{{role_path}}/vars'

- name: include os specific tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', python3_tasks_params) }}"
  vars:
    python3_tasks_params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
      paths:
        - '{{role_path}}/tasks'
