---
- name: "Install chrony packages"
  yum:
    name: "{{ chrony_packages }}"
    state: latest  

- name: "Create chrony configuration file"
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644

- name: "Enable chrony service"
  systemd:
    name: chronyd 
    enabled: yes

- name: "Start chrony service"
  systemd:
    name: chronyd
    state: started
