---
#
# rstudio-rpm
#
rstudio_rpm: rstudio-server
rstudio_rpm_version: 2023.06.0-421

rstudio_server: server.domain.tld
rstudio_port: 8787

rstudio_ssl_port: 8788
rstudio_ssl_copy: false
rstudio_ssl_crt: keyfile.pem
#rstudio_ssl_key: keyfile.key

rstudio_r: /usr/bin/R

#Wrap rsession with slurm srun?
#
# This feature adds a wrapper script and setups rstudio-service to
# use this script running new sesssions
#
rstudio_wrap_slurm: true
rstudio_srun_flags:
  - "--qos=limited-test-rstudio"

#SSSD Pam Authentication (replace /etc/pam.d/rstudio config file)
rstudio_sssd_pam: true

#SELinux (settings)
rstudio_selinux: true

#firewalld
rstudio_firewalld: true
