---
- name: "Install bcftools depended OS packages"
  yum:
    name: "{{ bcftools_os_packages }}"
    state: latest
  become: yes

# Is it already installed?
- name: "Check for bcftools installation @ {{ bcftools_install_dest }}/{{ bcftools_prefix }}"
  stat: path="{{ bcftools_install_dest }}/{{ bcftools_prefix }}"
  register: bcftools_installed

# Transfer, unpack and compile
- name: "Transfer, unpack and compile bcftools"
  block:
    - ansible.builtin.unarchive:
        src: "files/{{ bcftools_prefix }}.{{ bcftools_archive }}"
        dest: /tmp
        creates: /tmp/{{ bcftools_prefix }}
    - command: "./configure --prefix={{ bcftools_install_dest }}/{{ bcftools_prefix }} {{ bcftools_configure_flags | join(' ') }} {{ bcftools_configure_flags_user | join(' ') }}"
      args:
        chdir: /tmp/{{ bcftools_prefix }}
    - community.general.make:
        chdir: /tmp/{{ bcftools_prefix }}
    - community.general.make:
        chdir: /tmp/{{ bcftools_prefix }}
        target: install
      become: yes
  when: not bcftools_installed.stat.exists

- name: "Link bcftools parts (binaries, man and lib) to OS"
  block:
    - ansible.builtin.file:
        src: "{{ bcftools_install_dest }}/{{ bcftools_prefix }}"
        dest: "{{ bcftools_linkdir }}"
        state: link

    # Find & link binaries      
    - ansible.builtin.find:
        paths: "{{ bcftools_linkdir }}/bin"
      register: bcftools_binaries
      when: bcftools_dolink
    - ansible.builtin.file:
        src: "{{ item.path }}"
        path: "{{ bcftools_binary_dest }}/{{ item.path | basename }}"
        state: link
      with_items: "{{ bcftools_binaries.files }}"

    # Find & create man directories and link man files
    - ansible.builtin.find:
        paths: "{{ bcftools_linkdir }}/share/man"
        file_type: directory
      register: bcftools_man_dirs
    - ansible.builtin.file:
        path: "{{ bcftools_man_dest }}/{{ item.path | basename }}"
        owner: root
        group: root
        mode: 0755
      with_items: "{{ bcftools_man_dirs.files }}"

    - ansible.builtin.find:
        paths: "{{ bcftools_linkdir }}/share/man"
        file_type: file
        recurse: true
      register: bcftools_man_files
    - ansible.builtin.file:
        src: "{{ item.path }}"
        path: "{{ bcftools_man_dest }}/{{ item.path.split('/')[-2:]|join('/') }}"
        state: link
      with_items: "{{ bcftools_man_files.files }}"

    - command: mandb
      become: yes

  when: not bcftools_installed.stat.exists and bcftools_dolink
