---
- name: "Install packages"
  dnf:
    name: "{{ cluster_packages }}"
    state: latest

- name: "Install man-db package"
  dnf:
    name: man-db
    state: latest

- block:
  - name: "Create MANDATORY_MANPATHs folder"
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0775
      recurse: yes
    loop: "{{ cluster_mandatory_manpaths }}"
  - name: "Set MANDATORY_MANPATHs"
    lineinfile:
      path: "{{ cluster_man_db_path }}"
      regexp: 'MANDATORY_MANPATH                       {{ item }}'
      insertafter: '^MANDATORY_MANPATH'
      line: 'MANDATORY_MANPATH                       {{ item }}'
      state: present
    loop: "{{ cluster_mandatory_manpaths }}"
  when: cluster_mandatory_manpaths is defined

- block:
  - name: "Set bin MANPATH_MAPs"
    lineinfile:
      path: "{{ cluster_man_db_path }}"
      regexp: 'MANPATH_MAP     {{ item.bin }}          {{ item.man }}'
      insertafter: '^MANPATH_MAP'
      line: 'MANPATH_MAP     {{ item.bin }}          {{ item.man }}'
      state: present
    loop: "{{ cluster_manpath_maps }}"
  when: cluster_manpath_maps is defined

- name: "Run mandb to reconfigure man databases"
  command: mandb

# Set PATHs (create file in profile.d)
- block:
  - name: "Create PATH folder"
    file:
      path: "{{ item.location }}"
      state: directory
      owner: root
      group: root
      mode: 0775
      recurse: yes
    loop: "{{ cluster_paths }}"
  - name: "Create profile.d files with PATH info"
    template:
      src: path.sh.j2
      dest: "{{ cluster_profile_d_path }}/{{ item.name }}.sh"
      owner: root
      group: root
      mode: 0644
    loop: "{{ cluster_paths }}"
  when: cluster_paths is defined

- block:
  - name: "Make link for csh users"
    file:
      src: "{{ cluster_profile_d_path }}/{{ item.name }}.sh"
      dest: "{{ cluster_profile_d_path }}/{{ item.name }}.csh"
      state: link
    loop: "{{ cluster_paths }}"
  when: cluster_paths is defined

# Set security settings in limits.d
- block:
  - name: "Create nofile.conf in /etc/security/limits.d"
    template:
      src: nofile.conf.j2
      dest: "/etc/security/limits.d/nofile.conf"
      owner: root
      group: root
      mode: 0640
  when: cluster_nofile_soft is defined and cluster_nofile_hard is defined

# Copy script with numeric user environent variable
- block:
  - name: Copy numeric_user.sh to cluster
    copy:
      src: files/numeric_user.sh
      dest: "{{ cluster_profile_d_path }}/numeric_user.sh"
      owner: root
      group: root
      mode: u=rwx,g=rwx,o=rx
  - name: Link csh version
    file:
      src: "{{ cluster_profile_d_path }}/numeric_user.sh"
      dest: "{{ cluster_profile_d_path }}/numeric_user.csh"
      state: link
  when: cluster_numeric_user is defined and cluster_numeric_user
