---
# Preparations
- name: "Install Gatk depended OS packages"
  yum:
    name: "{{ gatk_os_packages }}"
    state: latest
  become: yes
  when: gatk_os_packages is defined

# Is it already installed?
- name: "Check for gatk installation @ {{ gatk_install_dest }}/{{ gatk_prefix }}"
  stat: path="{{ gatk_install_dest }}/{{ gatk_prefix }}"
  register: gatk_installed

#Transfer, unpack and compile
#
# Applies Patch for 4.4.0.0 that specifies java binary
#
- name: "Transfer, unpack and setup gatk"
  block:
    - ansible.builtin.unarchive:
        src: "files/{{ gatk_prefix }}.{{ gatk_archive }}"
        dest: "{{ gatk_install_dest }}/"
        creates: "{{ gatk_install_dest }}/{{ gatk_prefix }}"
    - file:
        src: "{{ gatk_install_dest }}/{{ gatk_prefix }}"
        dest: "{{ gatk_linkdir }}"
        state: link
      when: gatk_dolink
    - file:
        src: "{{ gatk_binary_source }}"
        dest: "{{ gatk_binary_dest }}"
        state: link
      when: gatk_dolink
    - file:
        src: "{{ gatk_linkdir }}/gatk-completion.sh"
        dest: "{{ gatk_bash_completion_folder }}/gatk-completion.sh"
        state: link
      when: gatk_dolink
  when: not gatk_installed.stat.exists
