---
#
# Source archive (prefix and archive), looks for (link) in files/ folder of role
#
plink19_prefix: plink-ng-2.00a5.10
plink19_archive: tar.gz

#Installation folder
plink19_install_dest: /opt/tools/versions

#Separate link dir (for different versions)
plink19_linkdir: /opt/tools/plink-ng-19

#Binaries (e.g. linking to location in PATH)
plink19_binary_source: /opt/tools/plink-ng-19/bin/plink
plink19_binary_dest: /opt/tools/bin/plink19

#Do the actual linking?
plink19_dolink: true
