---
#
# Source archive (prefix and archive), looks for (link) in files/ folder of role
#
samtools_prefix: samtools-1.19.2
samtools_archive: tar.bz2

#Installation folder
samtools_install_dest: /opt/tools/versions

#Separate link dir (for different versions, link to default version)
samtools_linkdir: /opt/tools/samtools

#Additional configure script flags
samtools_configure_flags_user:
  - "--with-htslib=/opt/tools/htslib"

#Where to link the binaries to
samtools_binary_dest: /opt/tools/bin

#Where to link the man files to
samtools_man_dest: /opt/tools/man

#Do the actual linking?
samtools_dolink: true
