---
# 11-04-2023 MV:
# Installation of static plink 1.9 according to situation
# with plink-ng-2.00a3.7 - plink_first_compile script
#
#
# Preparations
- name: "Install plink depended OS packages"
  yum:
    name: "{{ plink19_os_packages }}"
    state: latest
  become: yes

# Is it already installed?
- name: "Check for plink installation @ {{ plink19_install_dest }}/{{ plink19_prefix }}/bin/plink"
  stat: path="{{ plink19_install_dest }}/{{ plink19_prefix }}/bin/plink"
  register: plink19_installed

#Transfer, unpack and compile
#
# Two changes to plink Makefile (El7/12-04-2023):
#
# - Install prefix (PREFIX / DESTDIR)
# - Use gslcblas instead of cblas
#
- name: "Transfer, unpack and compile plink"
  block:
    - ansible.builtin.unarchive:
        src: "files/{{ plink19_prefix }}.{{ plink19_archive }}"
        dest: /tmp
        creates: /tmp/{{ plink19_prefix }}
    - ansible.builtin.lineinfile:
        path: /tmp/{{ plink19_prefix }}/1.9/Makefile
        regexp: '^PREFIX'
        line: "PREFIX ?=       {{ plink19_prefix }}"
        state: present
    - ansible.builtin.lineinfile:
        path: /tmp/{{ plink19_prefix }}/1.9/Makefile
        regexp: '^DESTDIR'
        line: "DESTDIR ?=      {{ plink19_install_dest }}/"
        state: present        
    - ansible.builtin.lineinfile:
        path: /tmp/{{ plink19_prefix }}/1.9/Makefile
        regexp: '^BLASFLAGS'
        line: "BLASFLAGS ?=   -L/usr/lib64/atlas -llapack -lblas -lgslcblas -latlas"
        state: present
    - command: ./plink_first_compile
      args:
        chdir: /tmp/{{ plink19_prefix }}/1.9
    - make:
        chdir: /tmp/{{ plink19_prefix }}/1.9
        target: install
    - file:
        src: "{{ plink19_install_dest }}/{{ plink19_prefix }}"
        dest: "{{ plink19_linkdir }}"
        state: link
      when: plink19_dolink
    - file:
        src: "{{ plink19_binary_source }}"
        dest: "{{ plink19_binary_dest }}"
        state: link
      when: plink19_dolink
  when: not plink19_installed.stat.exist
