---
htslib_os_packages:
  - zlib
  - zlib-devel
  - bzip2
  - bzip2-libs
  - bzip2-devel
  - xz
  - xz-lzma-compat
  - xz-devel
  - xz-libs
  - libcurl
  - libcurl-devel
#  - crypto-utils
  - openssl
  - openssl-libs

htslib_configure_flags:
  - "--enable-libcurl"
